# Site settings
title: EngineerBetter
email: contact@engineerbetter.com
description: > # this means to ignore newlines until "baseurl:"
  Cloud Foundry, BOSH and Concourse CI services in the United Kingdom
baseurl: "" # the subpath of your site, e.g. /blog/
timezone: Europe/London
twitter_username: engineerbetter
github_username:  engineerbetter

# Exclude directories
exclude: [ci]

# Build settings
markdown: kramdown

kramdown:
  input: GFM

excerpt_separator: <!--more-->

gems:
- jekyll-redirect-from