# Site settings
title: EngineerBetter
email: contact@engineerbetter.com
description: > # this means to ignore newlines until "baseurl:"
  We help you deliver the software that matters to your business, through Cloud Foundry PaaS and modern, effective
  methods of software development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: engineerbetter
github_username:  engineerbetter

# Build settings
markdown: kramdown
