# Site settings
title: EngineerBetter
email: contact@engineerbetter.com
description: > # this means to ignore newlines until "baseurl:"
  The UK Cloud Foundry specialists
baseurl: "" # the subpath of your site, e.g. /blog/
timezone: Europe/London
twitter_username: engineerbetter
github_username:  engineerbetter

# Build settings
markdown: kramdown

kramdown:
  input: GFM

excerpt_separator: <!--more-->
